export const teacherName = {
  status: 1,
  result: [
    {
      teacherName: "wang",
      teachers: [
        {
          name: "王金萍",
          id: "659befdda5f838b3673796b5",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "王晋",
          id: "659befdda5f838b3673796c6",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "王栋",
          id: "659befdda5f838b3673796d6",
          userPower: { grades: [] },
        },
        {
          name: "王凌",
          id: "659befdda5f838b3673796d7",
          userPower: { grades: [] },
        },
        {
          name: "王晔",
          id: "659befdda5f838b3673796d8",
          userPower: { grades: [] },
        },
      ],
    },
  ],
  time: 1747755137760,
};
export const master = {
  status: 1,
  result: [
    {
      teacherName: "",
      teachers: [
        {
          orgNum: "01",
          grade: "二年级",
          name: "姚文贇",
          id: "659befdda5f838b3673796e0",
          userPower: { grades: [] },
        },
        {
          orgNum: "02",
          grade: "二年级",
          name: "齐虹",
          id: "659befdda5f838b3673796c2",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          orgNum: "03",
          grade: "二年级",
          name: "陈奕",
          id: "659befdda5f838b3673796c8",
          userPower: { grades: [] },
        },
        {
          orgNum: "04",
          grade: "二年级",
          name: "王凌",
          id: "659befdda5f838b3673796d7",
          userPower: { grades: [] },
        },
        {
          orgNum: "01",
          grade: "三年级",
          name: "吴晓艳",
          id: "659befdda5f838b3673796d9",
          userPower: { grades: [] },
        },
        {
          orgNum: "02",
          grade: "三年级",
          name: "吴健群",
          id: "659befdda5f838b3673796c3",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          orgNum: "03",
          grade: "三年级",
          name: "洪源",
          id: "659befdda5f838b3673796cd",
          userPower: { grades: [] },
        },
        {
          orgNum: "04",
          grade: "三年级",
          name: "贲春梅",
          id: "659befdda5f838b3673796bb",
          userPower: {
            subjects: ["语文"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          orgNum: "01",
          grade: "四年级",
          name: "徐文燕",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          orgNum: "02",
          grade: "四年级",
          name: "杨¥",
          id: "659befdda5f838b3673796df",
          userPower: { grades: [] },
        },
        {
          orgNum: "03",
          grade: "åå¹´çº§",
          name: "éè´",
          id: "659befdda5f838b3673796c9",
          userPower: { grades: [] },
        },
        {
          orgNum: "04",
          grade: "åå¹´çº§",
          name: "é»ä½³å®",
          id: "659befdda5f838b3673796c4",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          orgNum: "01",
          grade: "äºå¹´çº§",
          name: "é©¬çè",
          id: "659befdda5f838b3673796c5",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          orgNum: "02",
          grade: "äºå¹´çº§",
          name: "éæ¾ä»ª",
          id: "659befdda5f838b3673796cc",
          userPower: { grades: [] },
        },
        {
          orgNum: "03",
          grade: "äºå¹´çº§",
          name: "åç§è²",
          id: "659befdda5f838b3673796d1",
          userPower: { grades: [] },
        },
      ],
    },
  ],
  time: 1747752957304,
};
export const type = {
  status: 1,
  result: [
    {
      teacherName: "科技",
      teachers: [
        {
          name: "王晔",
          id: "659befdda5f838b3673796d8",
          userPower: { grades: [] },
        },
        {
          name: "李群",
          id: "659befdda5f838b3673796cf",
          userPower: { grades: [] },
        },
        {
          name: "宋青云",
          id: "659befdda5f838b3673796d4",
          userPower: { grades: [] },
        },
        {
          name: "薛峰",
          id: "659befdda5f838b3673796da",
          userPower: { grades: [] },
        },
        {
          name: "周雅君",
          id: "659befdda5f838b3673796c0",
          userPower: {
            subjects: ["科技"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
      ],
    },
    {
      teacherName: "拓展（体）",
      teachers: [
        {
          name: "朱瑾",
          id: "659befdda5f838b3673796ea",
          userPower: { grades: [] },
        },
        {
          name: "刘岚",
          id: "659befdda5f838b3673796b7",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "王金萍",
          id: "659befdda5f838b3673796b5",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "朱佳玲",
          id: "659befdda5f838b3673796e9",
          userPower: { grades: [] },
        },
        {
          name: "贲春梅",
          id: "659befdda5f838b3673796bb",
          userPower: {
            subjects: ["语文"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "洪源",
          id: "659befdda5f838b3673796cd",
          userPower: { grades: [] },
        },
        {
          name: "吴健群",
          id: "659befdda5f838b3673796c3",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "吴晓艳",
          id: "659befdda5f838b3673796d9",
          userPower: { grades: [] },
        },
        {
          name: "朱雪龑",
          id: "659befdda5f838b3673796b8",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "徐文燕",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          name: "杨健",
          id: "659befdda5f838b3673796df",
          userPower: { grades: [] },
        },
        {
          name: "陈贇",
          id: "659befdda5f838b3673796c9",
          userPower: { grades: [] },
        },
        {
          name: "黄佳宁",
          id: "659befdda5f838b3673796c4",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "朱崎泓",
          id: "659befdda5f838b3673796b6",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "刘秀莲",
          id: "659befdda5f838b3673796d1",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "语文",
      teachers: [
        {
          name: "姚文贇",
          id: "659befdda5f838b3673796e0",
          userPower: { grades: [] },
        },
        {
          name: "齐虹",
          id: "659befdda5f838b3673796c2",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "éå¥",
          id: "659befdda5f838b3673796c8",
          userPower: { grades: [] },
        },
        {
          name: "çå",
          id: "659befdda5f838b3673796d7",
          userPower: { grades: [] },
        },
        {
          name: "è´²æ¥æ¢",
          id: "659befdda5f838b3673796bb",
          userPower: {
            subjects: ["è¯­æ"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "æ´ªæº",
          id: "659befdda5f838b3673796cd",
          userPower: { grades: [] },
        },
        {
          name: "å´å¥ç¾¤",
          id: "659befdda5f838b3673796c3",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "å´æè³",
          id: "659befdda5f838b3673796d9",
          userPower: { grades: [] },
        },
        {
          name: "å¾æç",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          name: "æ¨å¥",
          id: "659befdda5f838b3673796df",
          userPower: { grades: [] },
        },
        {
          name: "éè´",
          id: "659befdda5f838b3673796c9",
          userPower: { grades: [] },
        },
        {
          name: "é»ä½³å®",
          id: "659befdda5f838b3673796c4",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "æ´èå©·",
          id: "659befdda5f838b3673796c1",
          userPower: {
            subjects: ["éæ³"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "åç§è²",
          id: "659befdda5f838b3673796d1",
          userPower: { grades: [] },
        },
        {
          name: "æ±å´æ³",
          id: "659befdda5f838b3673796b6",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "é©¬çè",
          id: "659befdda5f838b3673796c5",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
      ],
    },
    {
      teacherName: "è±è¯­",
      teachers: [
        {
          name: "æ¿è¾",
          id: "659befdda5f838b3673796cb",
          userPower: { grades: [] },
        },
        {
          name: "æ±ææ´",
          id: "659befdda5f838b3673796bd",
          userPower: {
            subjects: ["è±è¯­"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "å¼ é",
          id: "659befdda5f838b3673796e8",
          userPower: { grades: [] },
        },
        {
          name: "æé",
          id: "659befdda5f838b3673796ca",
          userPower: { grades: [] },
        },
        {
          name: "å­æå®¹",
          id: "659befdda5f838b3673796d5",
          userPower: { grades: [] },
        },
        {
          name: "éæ¾ä»ª",
          id: "659befdda5f838b3673796cc",
          userPower: { grades: [] },
        },
        {
          name: "å¾è£å",
          id: "659befdda5f838b3673796de",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "å±æ¸¸",
      teachers: [
        {
          name: "æèµèµ",
          id: "659befdda5f838b3673796ce",
          userPower: { grades: [] },
        },
        {
          name: "è¢æå½±",
          id: "659befdda5f838b3673796e1",
          userPower: { grades: [] },
        },
        {
          name: "æ¨éª",
          id: "659befdda5f838b3673796bf",
          userPower: {
            subjects: ["é³ä¹"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "æ¨å¥",
          id: "659befdda5f838b3673796df",
          userPower: { grades: [] },
        },
        {
          name: "éè´",
          id: "659befdda5f838b3673796c9",
          userPower: { grades: [] },
        },
        {
          name: "é»ä½³å®",
          id: "659befdda5f838b3673796c4",
          userPower: {
            subjects: [
              "ç§æ",
              "æ展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
      ],
    },
    {
      teacherName: "拓展",
      teachers: [
        {
          name: "朱文洁",
          id: "659befdda5f838b3673796bd",
          userPower: {
            subjects: ["英语"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "张青",
          id: "659befdda5f838b3673796e8",
          userPower: { grades: [] },
        },
        {
          name: "房蕾",
          id: "659befdda5f838b3673796cb",
          userPower: { grades: [] },
        },
        {
          name: "杜雅",
          id: "659befdda5f838b3673796ca",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "美术",
      teachers: [
        {
          name: "邹圣劭",
          id: "659befdda5f838b3673796eb",
          userPower: { grades: [] },
        },
        {
          name: "宋青云",
          id: "659befdda5f838b3673796d4",
          userPower: { grades: [] },
        },
        {
          name: "曹程轩",
          id: "659befdda5f838b3673796c7",
          userPower: { grades: [] },
        },
        {
          name: "刘定斐",
          id: "659befdda5f838b3673796d0",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "音乐",
      teachers: [
        {
          name: "杨骏",
          id: "659befdda5f838b3673796bf",
          userPower: {
            subjects: ["音乐"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "袁晓影",
          id: "659befdda5f838b3673796e1",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "拓展（心）",
      teachers: [
        {
          name: "姚文贇",
          id: "659befdda5f838b3673796e0",
          userPower: { grades: [] },
        },
        {
          name: "朱雪龑",
          id: "659befdda5f838b3673796b8",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "陈奕",
          id: "659befdda5f838b3673796c8",
          userPower: { grades: [] },
        },
        {
          name: "王凌",
          id: "659befdda5f838b3673796d7",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "道法",
      teachers: [
        {
          name: "姚文贇",
          id: "659befdda5f838b3673796e0",
          userPower: { grades: [] },
        },
        {
          name: "朱雪龑",
          id: "659befdda5f838b3673796b8",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "陈奕",
          id: "659befdda5f838b3673796c8",
          userPower: { grades: [] },
        },
        {
          name: "王凌",
          id: "659befdda5f838b3673796d7",
          userPower: { grades: [] },
        },
        {
          name: "贲春梅",
          id: "659befdda5f838b3673796bb",
          userPower: {
            subjects: ["语文"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "洪源",
          id: "659befdda5f838b3673796cd",
          userPower: { grades: [] },
        },
        {
          name: "吴健群",
          id: "659befdda5f838b3673796c3",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "吴晓艳",
          id: "659befdda5f838b3673796d9",
          userPower: { grades: [] },
        },
        {
          name: "徐文燕",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          name: "杨健",
          id: "659befdda5f838b3673796df",
          userPower: { grades: [] },
        },
        {
          name: "陈贇",
          id: "659befdda5f838b3673796c9",
          userPower: { grades: [] },
        },
        {
          name: "黄佳宁",
          id: "659befdda5f838b3673796c4",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "戴苏婷",
          id: "659befdda5f838b3673796c1",
          userPower: {
            subjects: ["道法"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "刘秀莲",
          id: "659befdda5f838b3673796d1",
          userPower: { grades: [] },
        },
        {
          name: "郝曾仪",
          id: "659befdda5f838b3673796cc",
          userPower: { grades: [] },
        },
        {
          name: "马燕萍",
          id: "659befdda5f838b3673796c5",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
      ],
    },
    {
      teacherName: "信息科技",
      teachers: [
        {
          name: "宋青云",
          id: "659befdda5f838b3673796d4",
          userPower: { grades: [] },
        },
        {
          name: "吕俊",
          id: "659befdda5f838b3673796d2",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "体育",
      teachers: [
        {
          name: "张慧菁",
          id: "659befdda5f838b3673796e3",
          userPower: { grades: [] },
        },
        {
          name: "朱瑾",
          id: "659befdda5f838b3673796ea",
          userPower: { grades: [] },
        },
        {
          name: "许鑫",
          id: "659befdda5f838b3673796dd",
          userPower: { grades: [] },
        },
        {
          name: "张斌",
          id: "659befdda5f838b3673796e2",
          userPower: { grades: [] },
        },
        {
          name: "王栋",
          id: "659befdda5f838b3673796d6",
          userPower: { grades: [] },
        },
        {
          name: "徐敏",
          id: "659befdda5f838b3673796db",
          userPower: { grades: [] },
        },
        {
          name: "刘秀莲",
          id: "659befdda5f838b3673796d1",
          userPower: { grades: [] },
        },
      ],
    },
    {
      teacherName: "探究",
      teachers: [
        {
          name: "吴秋华",
          id: "659befdda5f838b3673796ba",
          userPower: {
            subjects: ["探究", "拓展"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "朱佳玲",
          id: "659befdda5f838b3673796e9",
          userPower: { grades: [] },
        },
        {
          name: "林赛赛",
          id: "659befdda5f838b3673796ce",
          userPower: { grades: [] },
        },
        {
          name: "徐文燕",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          name: "孙慈容",
          id: "659befdda5f838b3673796d5",
          userPower: { grades: [] },
        },
        {
          name: "薛峰",
          id: "659befdda5f838b3673796da",
          userPower: { grades: [] },
        },
        {
          name: "周雅君",
          id: "659befdda5f838b3673796c0",
          userPower: {
            subjects: ["科技"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
      ],
    },
    {
      teacherName: "数学",
      teachers: [
        {
          name: "朱佳玲",
          id: "659befdda5f838b3673796e9",
          userPower: { grades: [] },
        },
        {
          name: "王晔",
          id: "659befdda5f838b3673796d8",
          userPower: { grades: [] },
        },
        {
          name: "林赛赛",
          id: "659befdda5f838b3673796ce",
          userPower: { grades: [] },
        },
        {
          name: "李群",
          id: "659befdda5f838b3673796cf",
          userPower: { grades: [] },
        },
        {
          name: "朱雪龑",
          id: "659befdda5f838b3673796b8",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "张丽玲",
          id: "659befdda5f838b3673796e4",
          userPower: { grades: [] },
        },
        {
          name: "王金萍",
          id: "659befdda5f838b3673796b5",
          userPower: {
            subjects: [
              "科技",
              "拓展（体）",
              "语文",
              "英语",
              "唱游",
              "美术",
              "拓展",
              "音乐",
              "道法",
              "拓展（心）",
              "体育",
              "信息科技",
              "探究",
              "数学",
              "体健",
              "拓展（科）",
            ],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年级"],
          },
        },
        {
          name: "徐敏",
          id: "659befdda5f838b3673796db",
          userPower: { grades: [] },
        },
        {
          name: "张敏",
          id: "659befdda5f838b3673796e6",
          userPower: { grades: [] },
        },
        {
          name: "严明丽",
          id: "659befdda5f838b3673796bc",
          userPower: {
            subjects: ["数学"],
            grades: ["一年级", "二年级", "三年级", "四年级", "五年§"],
          },
        },
        {
          name: "åå²",
          id: "659befdda5f838b3673796b7",
          userPower: {
            subjects: [
              "ç§æ",
              "æå±ï¼ä½ï¼",
              "è¯­æ",
              "è±è¯­",
              "å±æ¸¸",
              "ç¾æ¯",
              "æå±",
              "é³ä¹",
              "éæ³",
              "æå±ï¼å¿ï¼",
              "ä½è²",
              "ä¿¡æ¯ç§æ",
              "æ¢ç©¶",
              "æ°å­¦",
              "ä½å¥",
              "æå±ï¼ç§ï¼",
            ],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
      ],
    },
    {
      teacherName: "ä½å¥",
      teachers: [
        {
          name: "å¯æä¹¦",
          id: "659befdda5f838b3673796be",
          userPower: {
            subjects: ["ä½è²"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "ä¸¥æä¸½",
          id: "659befdda5f838b3673796bc",
          userPower: {
            subjects: ["æ°å­¦"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
      ],
    },
    {
      teacherName: "æå±ï¼ç§ï¼",
      teachers: [
        {
          name: "å´ç§å",
          id: "659befdda5f838b3673796ba",
          userPower: {
            subjects: ["æ¢ç©¶", "æå±"],
            grades: ["ä¸å¹´çº§", "äºå¹´çº§", "ä¸å¹´çº§", "åå¹´çº§", "äºå¹´çº§"],
          },
        },
        {
          name: "æèµèµ",
          id: "659befdda5f838b3673796ce",
          userPower: { grades: [] },
        },
        {
          name: "å¾æç",
          id: "659befdda5f838b3673796dc",
          userPower: { grades: [] },
        },
        {
          name: "å­æå®¹",
          id: "659befdda5f838b3673796d5",
          userPower: { grades: [] },
        },
        {
          name: "èå³°",
          id: "659befdda5f838b3673796da",
          userPower: { grades: [] },
        },
      ],
    },
  ],
  time: 1747752971281,
};
